Christophe
FlavienBusseuil/bga-chrome-extension pull request #52
Opened 2023-06-09 16:05 UTC by cdelaforge

Let me know ;)

2023-06-29 20:15 UTC, FlavienBusseuil commented on src/css/tailwind.css
C'est étrange que ce fichier ait été mis à jour... normalement c'est du code auto-généré d'après les classes Tailwind utilisées. Je pense qu'il ne doit parser tes fichiers et y trouver des classes qui ressemble à du tailwind :thinking: , il faut que j'investigue ça.

2023-06-29 20:36 UTC, FlavienBusseuil requested changes
Super ! Bravo pour le boulot c'est super facile de s'y retrouver. :clap: 
Juste un mini commentaire et un autre truc que je dois regarder de mon côté.

Sinon quelques notes :
* Je me suis rendu compte que j'avais une config Prettier sur le projet mais pas prettier dans packages.json :facepalm: . J'ai poussé un commit pour l'ajouter et j'ai exécuter prettier sur tout le code. On sera aligné pour le formattage de nos fichiers :+1: 
* Je réalise que sur ce projet j'utilise Flow. Toi Typescript. C'est pas tant un problème tant que chacun joue dans sa cours. A voir si un jour on a un besoin d'uniformisation. Je suis pas contre l'idée de basculer à TS (j'ai l'habitude des deux).

2023-06-29 20:36 UTC, FlavienBusseuil commented on src/js/options.js
> +// @flow
Tu peux enlever tous les `// @flow` en haut dans plusieurs de tes fichiers puisque tu utilises typescript. Ça évitera que Flow rouspète de mon côté :smile:

2023-06-30 15:20 UTC, cdelaforge commented on src/css/tailwind.css
Je n'avais pas fait attention, je ne l'ai effectivement pas modifié intentionnellement en tout cas, c'est bizarre ...

2023-07-02 21:12 UTC, FlavienBusseuil commented on src/css/tailwind.css
Ouai effectivement je pense que le problème c'est que la config de Tailwind passe aussi sur tes fichiers :
```js
	content: [
		"./src/popup.html",
		"./src/options.html",
		"./src/js/**/*.{js,jsx}",
	],
```

Et comme il y a des strings dans les js qui se recouvrent avec les keywords de Tailwind ça les ajoutes automatiquements.
J'ai regarder sur la doc de Tailwind et j'ai pas vu d'option de config pour exclure des paths, on ne peut qu'en ajouter...
Je sais pas ce que t'en pense, est-ce qu'on est mieux de pas mettre le code au même niveau ? On s'en reparle.

2023-07-03 07:34 UTC, cdelaforge commented on src/css/tailwind.css
J'ai trouvé la solution pour exclure certains paths finalement.  C'est expliqué ici : https://github.com/mrmlnc/fast-glob et en résumé il suffit de préciser un "!" devant le path dans la config.
Du coup j'ai refais un push et comme tu pourras voir le fichier tailwind.css est revenu au même état que sur la branche master (à la casse près, mais ça on s'en fiche :) )

Ceci dit, je pense que ce ne serait pas forcément du luxe à l'occasion de refaire la page des options en utilisant un peu Tailwind pour plus de cohérence dans les styles, d'autant plus que je ne suis pas super satisfait du style actuel.
Mais ça peut être fait plus tard aussi, ce n'est pas forcément urgent.

Par contre je pense qu'il vaut mieux exclure src/js/ui/content comme je l'ai fait, j'utilise pas mal de classes css qui sont définies par BGA et vaut mieux pas que Tailwind s'en même du coup !

Qu'est ce que tu en penses ?

2023-07-04 18:28 UTC, FlavienBusseuil commented on src/css/tailwind.css
Good job !

Effectivement si tu veux passer à Tailwind ça pourrait être chouette et l'occasion pour toi de t'essayer si jamais t'as jamais utilisé la techno :wink:. Mais on pourra s'en reparler. Bon maintenant je vais voir pour faire une version rapidement. :)

2023-07-04 18:31 UTC, FlavienBusseuil approved these changes
:muscle:

2023-07-06 19:47 UTC, merged